import { GitHubLogoIcon, InstagramLogoIcon, LinkedInLogoIcon } from "@radix-ui/react-icons";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="hidden md:block">
          <SocialMediaful />
        </div>
        <main className={`max-w-6xl mx-auto items-center min-h-screen `}>
          {children}
        </main>
      </body>
    </html>
  );
}

export function SocialMedia() {
  return (
    <div className="flex pt-6 gap-6 justify-center ">
      <div className="w-8 h-8 flex justify-center items-center  text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://www.instagram.com/mrjustizzy"}>
          <InstagramLogoIcon className="w-6 h-6" />
        </Link>
      </div>
      <div className="w-8 h-8 flex justify-center items-center rounded-full text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://github.com/akinleyeisrael"}>
          <GitHubLogoIcon className="w-6 h-6" />
        </Link>
      </div>
      <div className="w-8 h-8 flex justify-center items-center rounded-full text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://www.linkedin.com/in/akinola-akinleye-1612b6224/"}>
          <LinkedInLogoIcon className="w-6 h-6" />
        </Link>
      </div>
    </div>
  );
}
export function SocialMediaful() {
  return (
    <div className="grid grid-cols-3 sm:py-10  sm:grid-cols-1 gap-6 fixed  sm:px-12 ">
      <div className="w-8 h-8 flex justify-center items-center  text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://www.instagram.com/mrjustizzy"}>
          <InstagramLogoIcon className="w-6 h-6" />
        </Link>
      </div>
      <div className="w-8 h-8 flex justify-center items-center rounded-full text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://github.com/akinleyeisrael"}>
          <GitHubLogoIcon className="w-6 h-6" />
        </Link>
      </div>
      <div className="w-8 h-8 flex justify-center items-center rounded-full text-slate-200 hover:text-lime-300">
        <Link target="_blank" href={"https://www.linkedin.com/in/akinola-akinleye-1612b6224/"}>
          <LinkedInLogoIcon className="w-6 h-6" />
        </Link>
      </div>
    </div>
  );
}